# Site settings
name: Kyle Maxwell
email: yourmom@example.com
description: "So much hacking, so little time"
url: "http://xwell.org" # the base hostname & protocol for your site
twitter: kylemaxwell
github: krmaxwell
google: KyleMaxwell
instagram: technoskald

# Build settings
markdown: redcarpet
highlighter: pygments

# Octopress migration
permalink: /:year/:month/:day/:title/

# Solarized
paginate: 10
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', '/vendor']
